### ISSUE TITLE
浏览主机明细，提示 Dashboard not found 【急急急！！！】

### ISSUE THREAD

**Issue by rayshen3** [starsliao/Prometheus#102]
centos 7 
grafana 8.0和7.5都试过
1-node-exporter-for-prometheus-dashboard-cn-v20201010   最新版

dashboard上点击主机名，跳转链接如下
http://192.168.10.1:3000/d/9CWBz0bik/node-exporter?orgId=1&var-job=node&var-hostname=All&var-node=192.168.10.2%3A9100&var-device=All&var-origin_prometheus=

直接提示
![image](https://user-images.githubusercontent.com/9734936/121339245-db5ffe00-c950-11eb-80f5-f0b53c7be031.png)

是不是依赖另外的node-exporter dashboard呢？  我在grafana官网能搜到 ”node-exporter”  相关的dashboard，不是这个吧。

其实就是想点击主机名，展示的还是当前的dashboard，只是过滤下这个这个主机就很好，  比如跳转到
http://192.168.10.1:3000/d/l9Vnq_6Gk/1-node-exporter-for-prometheus-dashboard-cn-v20201010?orgId=1&var-origin_prometheus=&var-job=node&var-hostname=All&var-node=192.168.10.2:9100&var-device=All&var-interval=2m&var-maxmount=%2Fhome&var-show_hostname=dockerserver&var-total=5

有没有其它解决办法？ 辛苦帮忙看下，感谢。
@starsliao

**Comment by rayshen3** [comment]
解决了，我真TM是个天才  /鬼脸
1、安装node export full 这个dashboard  https://grafana.com/grafana/dashboards/1860
2、json方式编辑node export full，修改最后那个UID，改为 “9CWBz0bik” ，保存
3、然后在1-node-exporter-for-prometheus-dashboard-cn-v20201010 上点击资源总览中的IP跳转主机详情，直接就到了node export full中

**Comment by brotherxian** [comment]
你🐂🍺plus了

**Comment by CoderXiaohui** [comment]
你🐂🍺plus了

**Comment by irisrain** [comment]
牛。。。这个uid哪找的，厉害了
