### ISSUE TITLE
当 Pod 发生重启时，通过 sum 会重复计算内存使用值

### ISSUE THREAD

**Issue by ixiaoyi93** [starsliao/Prometheus#103]
具体如下所示：
![image](https://user-images.githubusercontent.com/34268642/122741531-a0968800-d2b7-11eb-8343-10e566779a45.png)

当我们的 Pod 发生异常重启时，会重复出现多个相同指标。此时在 grafana 查看面板时：
![image](https://user-images.githubusercontent.com/34268642/122741620-b441ee80-d2b7-11eb-9b4e-188b30153d4e.png)

大佬可在自己环境进行测试，如果我提供的数据有误，请及时纠正我的测试方式及数据。

**Comment by starsliao** [comment]
我看这个图， sum by container 是计算的这个容器的所有pod使用的working_set的总和呢。 不是单个pod的内存使用呀
