### ISSUE TITLE
几个集群都安装了k8s-prometheus，如何接入同一个grafana中的该模板

### ISSUE THREAD

**Issue by nekodori** [starsliao/Prometheus#106]
grafana中的datasources设置了几个集群的prometheus数据源，在dashboard中，edit模块，选择其他prometheus数据源时，上面会显示no data。每个集群自己的grafana导入该模板，是能正常显示的。请教下一个grafana怎么接入多个集群的prometheus的数据。是修改variables中origin_prometheus中的什么参数呢

**Comment by starsliao** [comment]
建议你使用Prometheus的外部系统标签：external_labels，可用于支持多个Prometheus接入VictoriaMetrics或Thanos等第三方存储使用remote_write方式的场景。
在grafana中直接接入remote_write的数据源，然后通过external_labels来选择查看不同的prometheus
