### ISSUE TITLE
To display the system are down or not reachable 

### ISSUE THREAD

**Issue by maneshmohanan1** [starsliao/Prometheus#108]
Dear Brother, 
 How can I display the server which is currently down

**Comment by maneshmohanan1** [comment]
![image](https://user-images.githubusercontent.com/68895389/132870501-3dfd6508-804f-4e2d-bb46-d6be2d443b37.png)

**Comment by starsliao** [comment]
编辑表格，增加一个up的promql，标签为node_exporter。
