### ISSUE TITLE
pod容器内存使用率 数据百分比不显示

### ISSUE THREAD

**Issue by yuanhaishan** [starsliao/Prometheus#116]
> pod容器内存使用率的图表数据百分比不显示  鼠标放在图表上方有对应的监控项 但是后面没有跟上百分比
![微信图片_20220106193547](https://user-images.githubusercontent.com/53658688/148377148-016bc420-1fb9-4c3d-8317-99555f0a7bc2.png)

**Comment by starsliao** [comment]
pod的limit有设置么？有limit才能计算百分比

**Comment by yuanhaishan** [comment]
感谢感谢 是这个原因
