### ISSUE TITLE
grafana显示不完整

### ISSUE THREAD

**Issue by waitsaber** [starsliao/Prometheus#119]
当我把显示的时间范围改到30天后图像的数据只有2个星期的，我能确定我的机器在运行时间不低于30天且都在监控，我应该修改哪里才能够显示更长的时间呢？
![image](https://user-images.githubusercontent.com/67093172/159337346-ace74218-7f04-4c55-aab4-b31986d6035b.png)

**Comment by starsliao** [comment]
可能是指标的标签或者名称在那个时间修改过导致匹配不到就没有之前的数据了.你可以到prometheus里面查询下 去掉部分标签看看
