### ISSUE TITLE
Dashboard English Version 

### ISSUE THREAD

**Issue by RonZhang724** [starsliao/Prometheus#12]
Thanks for sharing the dashboard, and it looks great. I was wondering if there is an english version of the dashboard?

**Comment by cavamagie** [comment]
pleae




















very great

**Comment by skyducks** [comment]
Hi, I translated it to English. It is not perfect yet, but it was helpful for non-native Chinese like me.
https://github.com/skyducks/Prometheus/tree/translation

**Comment by marionxue** [comment]
wow. so cool.

**Comment by starsliao** [comment]
Hi all, I released  an English version of the dashboard。

### 1 Node Exporter for Prometheus Dashboard English Version UPDATE 1102
[https://grafana.com/grafana/dashboards/11074](https://grafana.com/grafana/dashboards/11074)
