### ISSUE TITLE
部分图标No data

### ISSUE THREAD

**Issue by 276649602** [starsliao/Prometheus#127]
![111](https://user-images.githubusercontent.com/98567619/202646820-bfd524ae-c1b2-4781-be68-954d12d1b729.PNG)
![222](https://user-images.githubusercontent.com/98567619/202646850-2e1a0ede-7937-42ea-900a-45d7379190e1.PNG)

**Comment by 276649602** [comment]
prometheus上无法查询到container_spec_cpu_quota指标，应该如何解决？
![图片](https://user-images.githubusercontent.com/98567619/202670630-3764c0f5-a413-4339-a1f9-9cf05a10e1da.png)

**Comment by xingxing122** [comment]
你的问题解决了么

**Comment by starsliao** [comment]
pod的cpu 内存使用率是需要为每个微服务配置limit才能计算使用率的.
