### ISSUE TITLE
blackbox_exporter图表不一致

### ISSUE THREAD

**Issue by kerven88** [starsliao/Prometheus#13]
你好版主，我导入了你的blackbox模板后，发现状态明细展示跟你的不一样，没有domain，连通性，ssl显示也不一样，是模板问题吗？

**Comment by kerven88** [comment]
原来是grafana版本问题，升级后正常，谢谢！

**Comment by Ansen** [comment]
Grafana v7.1.1 (3039f9c3bd) 遇到同样的问题

**Comment by starsliao** [comment]
很抱歉，这个版本很久没维护了，近期会会优化下发布一个改进的版本。
