### ISSUE TITLE
绑定IP看板

### ISSUE THREAD

**Issue by 330722640** [starsliao/Prometheus#14]
Hi，我想要创建多个看板，每个看板绑定一个固定IP，应该如何修改JSON文件？

**Comment by starsliao** [comment]
你可以把grafana里面$node这个变量设置为一个固定的值就行了。 
例如：
label_values(node_exporter_build_info{instance="192.168.200.150:9100"},instance)

**Comment by 330722640** [comment]
谢谢~
还有个问题，我从现有得到配置中拷贝了JSON内容，并修改了以下内容，目的是同时保留多个看板
  "title": "1 Node Exporter 0.16 0.17 for Prometheus 监控展示看板",
  "uid": "9CWBz0bik",
保存的时候却覆盖了原本的看板，看板管理中始终只有一个，请问是不是还有其他唯一标记位？

**Comment by starsliao** [comment]
你修改好变量后，左侧菜单最后就有个save as的按钮  另存一份就好了呀。

**Comment by 330722640** [comment]
好的，十分感谢
