### ISSUE TITLE
安装新版本后, 不显示任何指标

### ISSUE THREAD

**Issue by andy-zhangtao** [starsliao/Prometheus#2]
浏览器控制台显示以下错误:
react-dom.production.min.js:171 TypeError: Cannot read property 'exports' of undefined
    at e.loadPlugin (DashboardGrid.tsx:166)
    at e.componentDidMount (DashboardGrid.tsx:208)
    at da (react-dom.production.min.js:213)
    at ca (react-dom.production.min.js:205)
    at la (react-dom.production.min.js:204)
    at Fo (react-dom.production.min.js:200)
    at Object.enqueueSetState (react-dom.production.min.js:130)
    at r.y.setState (react.production.min.js:13)
    at r.i.strategisedSetState (react-sizeme.js:308)
    at react-sizeme.js:336
io @ react-dom.production.min.js:171

Grafana version: v5.4.0

**Comment by zhoujw8792** [comment]
也遇到此问题

**Comment by starsliao** [comment]
我测试了下 Grafana v5.4.2 + node_exporter 0.17 是正常的哦。

**Comment by zhoujw8792** [comment]
安装版本：node_exporter-0.17.0.linux-amd64、grafana-5.4.0、prometheus-2.5.0.linux-amd64
操作系统：CentOS Linux release 7.3.1611 (Core) 
上面还是不行，浏览器F12报以下错误：
![image](https://user-images.githubusercontent.com/546604/50071117-92111680-020b-11e9-9f70-16f0fd0982bc.png)
打开Grafana页面不显示
![image](https://user-images.githubusercontent.com/546604/50071132-a48b5000-020b-11e9-869a-5f362d015a46.png)

**Comment by ritayzy** [comment]
我也遇到了同样的问题

grafana-5.4.2 + node_exporter-0.17.0 + prometheus-2.6.0

**Comment by ritayzy** [comment]
我退回到 grafana-5.3.0 就好了 @starsliao @zhoujw8792

**Comment by starsliao** [comment]
我在导入别人的看板的时候发现了这样的问题，最后检查到是因为某些图形插件未安装引起的。
对于本看板，是需要先安装饼图插件的。所以报错可能是因为饼图插件未安装或更新引起的。
请尝试下：
`grafana-cli plugins install grafana-piechart-panel`
或
`grafana-cli plugins upgrade grafana-piechart-panel`
然后重启grafana-server，请确保在add panel时候能正常选择增加使用饼图。
@andy-zhangtao @zhoujw8792 @ritayzy
