### ISSUE TITLE
这回是真的问题，哈哈，没图

### ISSUE THREAD

**Issue by baosong818** [starsliao/Prometheus#22]
就是个黑框，从新编
![1](https://user-images.githubusercontent.com/1435453/62670002-3ecf1c80-b9c4-11e9-9cf5-518313b1ee64.png)
![2](https://user-images.githubusercontent.com/1435453/62670004-3ecf1c80-b9c4-11e9-8b13-2dc1030a1304.png)

辑又是一个黑框

**Comment by baosong818** [comment]
重启了所有docker服务

**Comment by starsliao** [comment]
> 重启了所有docker服务

之前有朋友遇到这个问题，部分版本的grafana，有某些图形插件未安装会有这样的问题。
你可以尝试下安装新版本的grafana，并且更新下这个看板（这个看板更新了，取消了饼图）。
