### ISSUE TITLE
网络宽带不显示

### ISSUE THREAD

**Issue by happinesslijian** [starsliao/Prometheus#24]
网络进宽带不显示
网络出宽带不显示
默认表达式是：
irate(node_network_receive_bytes_total{instance=~'$node',device=~'$nic'}[5m])*8
正确表达式是：（有待验证）
进宽带：
irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8
出宽带：
irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8
请核实表达式并更新！

**Comment by 54853315** [comment]
有意义的建议，在我的使用过程中将`node=~"^$Node$",` 从规则中去掉后，可以正常显示网络流量了。

因本人对P&G不是很熟悉，不太确定是否少装了什么东东。

![image](https://user-images.githubusercontent.com/1081252/109462789-f9d77300-7a9e-11eb-98b2-a905ddfe110a.png)
