### ISSUE TITLE
不显示硬件温度

### ISSUE THREAD

**Issue by Feeeenng** [starsliao/Prometheus#25]
Node_exporter 版本 0.18.1

原因是 这个版本 没有node_hwmon_temp_celsius 这个指标了

请问怎么解决呢

**Comment by starsliao** [comment]
> Node_exporter 版本 0.18.1
> 
> 原因是 这个版本 没有node_hwmon_temp_celsius 这个指标了
> 
> 请问怎么解决呢

我这边安装的也是0.18.1 ，我查了下 虚拟机会没有这个指标，真实PC机，服务器都有这个指标的。

**Comment by Feeeenng** [comment]
多谢
