### ISSUE TITLE
【各分区可用空间】这一栏有问题

### ISSUE THREAD

**Issue by zealinux** [starsliao/Prometheus#26]
分区错误如下：

```
/etc/hostname
/etc/hosts
/etc/resolv.conf
```

**Comment by starsliao** [comment]
> 区错误如下：
> 
> ```
> /etc/hostname
> /etc/hosts
> /etc/resolv.conf
> ```

没看明白 你这个是什么错误？你可以看下表达式里面的取值。

**Comment by zealinux** [comment]
@starsliao 不是应该来看各个分区的可用空间吗？
比如正确的应该是：/, /mnt,或者/dev/shm等

但是我这里是显示这三个文件，这是怎么原因？
```
/etc/hostname
/etc/hosts
/etc/resolv.conf
```
这三个是文件啊，当然显示的可用空间都是一样的，都是系统磁盘的分区剩余。

**Comment by zealinux** [comment]
![](https://www.png8.com/imgs/2019/11/830b4ee65f22b190.jpg)

**Comment by starsliao** [comment]
> @starsliao 不是应该来看各个分区的可用空间吗？
> 比如正确的应该是：/, /mnt,或者/dev/shm等
> 
> 但是我这里是显示这三个文件，这是怎么原因？
> 
> ```
> /etc/hostname
> /etc/hosts
> /etc/resolv.conf
> ```
> 
> 这三个是文件啊，当然显示的可用空间都是一样的，都是系统磁盘的分区剩余。

检查分区是根据node_filesystem_size_bytes 这个指标来的，取的是mountpoint这个标签。
按你说的可能是你把这几个文件挂载到容器里了 所有会显示出来。
你可以在服务器里执行df 查看下。
你可能需要根据你的情况加上一些标签来过滤出正确的结果。
比如我这边只取ext4或者xfs的类型的挂载点：
node_filesystem_size_bytes{instance=~'$node',fstype=~"ext4|xfs"}
