### ISSUE TITLE
undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by chenfanlinux** [starsliao/Prometheus#27]
错误：undefined is not iterable (cannot read property Symbol(Symbol.iterator))，我直接报这个错误。

**Comment by starsliao** [comment]
> 错误：undefined is not iterable (cannot read property Symbol(Symbol.iterator))，我直接报这个错误。

### 兼容性版本说明：
如果你导入看板之后报错：
```
Failed create dashboard model
Cannot read property 'Symbol(Symbol.iterator)' of undefined
```
说明你的grafana版本过低，不支持新增的BAR GAUGE图表，建议升级到**最新版本的grafana**，或者重新导入不带BAR GAUGE的版本：
[https://grafana.com/grafana/dashboards/11174](https://grafana.com/grafana/dashboards/11174)
