### ISSUE TITLE
8989模板报错

### ISSUE THREAD

**Issue by chenfanlinux** [starsliao/Prometheus#28]
Failed create dashboard model
undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by starsliao** [comment]
### 兼容性版本说明：
如果你导入看板之后报错：
```
Failed create dashboard model
Cannot read property 'Symbol(Symbol.iterator)' of undefined
```
说明你的grafana版本过低，不支持新增的BAR GAUGE图表，建议升级到**最新版本的grafana**，或者重新导入不带BAR GAUGE的版本：
[https://grafana.com/grafana/dashboards/11174](https://grafana.com/grafana/dashboards/11174)

另外 原看板的ID是**8919**，不是8989.
