### ISSUE TITLE
温度指标没有

### ISSUE THREAD

**Issue by cnm4ak** [starsliao/Prometheus#3]
node_hwmon_temp_celsius{instance="$node"}

prometheus 没有这项 是怎么回事？

node_hwmon_temp_celsius 我是0.17版本

**Comment by starsliao** [comment]
我安装了下0.17的 node_exporter 是有node_hwmon_temp_celsius这项的。
# TYPE node_hwmon_temp_celsius gauge
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp1"} 72
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp10"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp11"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp12"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp13"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp14"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp2"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp3"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp4"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp5"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_0",sensor="temp6"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp1"} 74
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp10"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp11"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp12"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp13"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp14"} 66
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp2"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp3"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp4"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp5"} 67
node_hwmon_temp_celsius{chip="platform_coretemp_1",sensor="temp6"} 68
