### ISSUE TITLE
No swap causes NaN

### ISSUE THREAD

**Issue by JonathanSendGrid** [starsliao/Prometheus#30]
When a node does not have swap defined, then it causes the graph to look like 100% and NaN is the value
![Screen Shot 2019-11-26 at 10 53 12 AM](https://user-images.githubusercontent.com/13321921/69654840-13d40b80-103b-11ea-8696-9c7945862fcd.png)

Adding 1 byte to each will cause it to evaluate to 0%. If the node uses swap, then the 1-byte change should be non-impacting

`(1 - ((node_memory_SwapFree_bytes{instance=~"$node"} + 1)/ (node_memory_SwapTotal_bytes{instance=~"$node"} + 1))) * 100`

**Comment by starsliao** [comment]
> When a node does not have swap defined, then it causes the graph to look like 100% and NaN is the value
> ![Screen Shot 2019-11-26 at 10 53 12 AM](https://user-images.githubusercontent.com/13321921/69654840-13d40b80-103b-11ea-8696-9c7945862fcd.png)
> 
> Adding 1 byte to each will cause it to evaluate to 0%. If the node uses swap, then the 1-byte change should be non-impacting
> 
> `(1 - ((node_memory_SwapFree_bytes{instance=~"$node"} + 1)/ (node_memory_SwapTotal_bytes{instance=~"$node"} + 1))) * 100`

Thank you, I used it this way
