### ISSUE TITLE
内存使用率看板报错

### ISSUE THREAD

**Issue by chenjinxuan** [starsliao/Prometheus#31]
内存，最大分区，交换分区使用率看板报错

![image](https://user-images.githubusercontent.com/25172225/69713949-6cd99780-1140-11ea-8cff-48026d15b2db.png)

**Comment by chenjinxuan** [comment]
看报错原因是指标同一时间有多个不唯一

**Comment by starsliao** [comment]
新版本中这个值是使用Bar Gauge来展示的，选择多主机时，多个值会显示多条数据。
