### ISSUE TITLE
Dashboard combine 2 job to 1 job

### ISSUE THREAD

**Issue by PePoDev** [starsliao/Prometheus#32]
First of all, Thanks for awesome dashboard.
It's very cool and look interesting.

But I have a little problem with it.

From my prometheus config file
![image](https://user-images.githubusercontent.com/15852891/69936534-a6c4e800-150a-11ea-90e3-89808fc41db6.png)

And in dashboard on grafana
![image](https://user-images.githubusercontent.com/15852891/69936686-163ad780-150b-11ea-93b1-80e4cbf3d301.png)

All of job name is working well.
But only ***csag-resource*** and ***csag-sv2*** look like that combine metrics from 2 job to the same job on dashboard.

Result on job ***csag-resource*** is same as ***csag-sv2*** on dashboard

Do you have any reason about that result ?

**Comment by PePoDev** [comment]
The issues is server that has same hostname.
But why this look hostname first ?
It's should look job name before see hostname in selected job ?

**Comment by starsliao** [comment]
Thanks， I will fix this bug and update the variable `$ node` to` label_values (node_uname_info {nodename = ~ "$ hostname", job = ~ "$ job"}, instance) `
