### ISSUE TITLE
你好，ext3的文件系统无法显示磁盘的使用情况

### ISSUE THREAD

**Issue by cdy668** [starsliao/Prometheus#37]
![image](https://user-images.githubusercontent.com/48209708/71463594-db6a4d80-27f1-11ea-9c02-06ac4ddc9f16.png)
如图 所示 经过测试ext3格式的分区不能获取到数据

**Comment by starsliao** [comment]
> ![image](https://user-images.githubusercontent.com/48209708/71463594-db6a4d80-27f1-11ea-9c02-06ac4ddc9f16.png)
> 如图 所示 经过测试ext3格式的分区不能获取到数据

我配置的表达式是只获取ext4和xfs  ，你可以编辑修改下增加表达式增加上ext3
