### ISSUE TITLE
ENV not found

### ISSUE THREAD

**Issue by marksugar** [starsliao/Prometheus#4]
老哥， 你第一个ENV环境变量是怎么键入的，node_exporter_build_info中并没有这个环节变量。后面的那些也没显示，就显示了ip，不过我出图了，图像很漂亮
我不清楚是不是我使用consul+registrator自动发现导致的。。。。
不过我发现你使用的应该是物理机，并且运行了openstack，我不清楚是否于此有关，如果是这个直接运行在物理机，那可能我使用不了

**Comment by marksugar** [comment]
我修改了变量，可以用了

**Comment by starsliao** [comment]
env是我在prometheus中自定义的标签。
是在consul的service中定义的。
```
      - source_labels:  ["__meta_consul_service"]
        target_label: "env"
```

**Comment by starsliao** [comment]
env是我在prometheus中自定义的标签。
是在consul的service中定义的。
```
      - source_labels:  ["__meta_consul_service"]
        target_label: "env"
```
@marksugar
