### ISSUE TITLE
Blackbox Exporter data source not Displaying on panel

### ISSUE THREAD

**Issue by pir8g33k** [starsliao/Prometheus#40]
Blackbox Exporter data source not Displaying on panel, and some panel seem different from the image on grafana dashboard and its not displaying like ssl certificate monitoring and etc, i need your help please thanks

https://grafana.com/grafana/dashboards/9965

![image](https://user-images.githubusercontent.com/63558386/79465422-e7427f80-802d-11ea-9cdc-afc6cc0f84cc.png)

**Comment by starsliao** [comment]
> Blackbox Exporter data source not Displaying on panel, and some panel seem different from the image on grafana dashboard and its not displaying like ssl certificate monitoring and etc, i need your help please thanks
> 
> https://grafana.com/grafana/dashboards/9965
> 
> ![image](https://user-images.githubusercontent.com/63558386/79465422-e7427f80-802d-11ea-9cdc-afc6cc0f84cc.png)

This may be that some variables cannot be obtained, resulting in the expression not being executed.

Please check the variable settings of grafana Kanban and the expression of the chart

**Comment by pir8g33k** [comment]
yes i was able to fixed this already, anyway do you have skype, whatsapps or any social media to contact you? thanks and looking for your fast response

**Comment by starsliao** [comment]
> 是的，我已经能够解决此问题，无论如何，您是否有Skype，whatsapps或任何社交媒体与您联系？谢谢，期待您的快速回复

wechat：starsliao
