### ISSUE TITLE
Uptime issue

### ISSUE THREAD

**Issue by xfgavin** [starsliao/Prometheus#41]
Hi there,

Nice dashboard! Thanks.

Here is one suggestion: The uptime panel is using sum. Results could be not helpful when viewing multiple nodes in the same time. max might be better.

**Comment by starsliao** [comment]
> Hi there,
> 
> Nice dashboard! Thanks.
> 
> Here is one suggestion: The uptime panel is using sum. Results could be not helpful when viewing multiple nodes in the same time. max might be better.

你好，发布了一个新版本，uptime只显示当前主机的启动时间，整体的信息展示在整体资源汇总表内。
