### ISSUE TITLE
wmi_exporter监控windows数据好像不正确,感觉数据源有问题

### ISSUE THREAD

**Issue by jschunlei** [starsliao/Prometheus#42]
上面汇总的数据,内存使用率 磁盘使用率 带宽使用率,数值永远是一样的
而且下面的数据感觉也不对,刚添加的节点, 竟然有历史数据

应该是有很多panel没有添加数据源引起的, 检查每个panel的datasource后,数据显示正常了

![windows](https://user-images.githubusercontent.com/9960265/81521423-c72a8580-9379-11ea-84d1-2798dccda503.png)

**Comment by jschunlei** [comment]
[wmi_exporter.zip](https://github.com/starsliao/Prometheus/files/4607486/wmi_exporter.zip)

这是修改后的json文件

**Comment by starsliao** [comment]
> [wmi_exporter.zip](https://github.com/starsliao/Prometheus/files/4607486/wmi_exporter.zip)
> 
> 这是修改后的json文件

谢谢，可能我这边使用的数据源是默认数据源，导出的时候没设置好，之后更新一个新的模板，windows的模板最近做了很多图表展示的优化。
