### ISSUE TITLE
Consider moving to a non contaminating license (eg. Apache 2)

### ISSUE THREAD

**Issue by PierreBesson** [starsliao/Prometheus#48]
First of all, thank you so much for this repo and dashboard which is extremely well done and useful to us.

As part of our internal infrastructure monitoring, we would like to do an internal fork of your node_exporter dashboard. However, the GPL license is preventing us to import this code into our own internal repo because of the "disclose source" clause of the GPL (see https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)).

Is the choice of GPL on purpose or would you consider switching to a more permissive license? Maybe, it could even encourage us or other enterprise users to contribute PRs in the future.
Thank you ! 谢谢 ！

**Comment by starsliao** [comment]
> First of all, thank you so much for this repo and dashboard which is extremely well done and useful to us.
> 
> As part of our internal infrastructure monitoring, we would like to do an internal fork of your node_exporter dashboard. However, the GPL license is preventing us to import this code into our own internal repo because of the "disclose source" clause of the GPL (see https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)).
> 
> Is the choice of GPL on purpose or would you consider switching to a more permissive license? Maybe, it could even encourage us or other enterprise users to contribute PRs in the future.
> Thank you ! 谢谢 ！

Okay, I have modified it to Apache-2.0 License。
