### ISSUE TITLE
中文兼容版json报错“Only queries that return single series/table is supported”

### ISSUE THREAD

**Issue by Leif160519** [starsliao/Prometheus#49]
grafana版本：7.0.6
prometheus版本：2.19.2
触发条件：当工具栏-IP（自动关联主机名）选择All的时候，内存使用率，最大分区使用率和交换分区使用率就会报“Only queries that return single series/table is supported”的错误。选择任意一台机器之后问题消失。只要选择All或者主机只有一台的情况下就会出现这种情况

![image.png](https://b3logfile.com/file/2020/07/image-57daa004.png)

![image.png](https://b3logfile.com/file/2020/07/image-13def380.png)

**Comment by starsliao** [comment]
> grafana版本：7.0.6
> prometheus版本：2.19.2
> 触发条件：当工具栏-IP（自动关联主机名）选择All的时候，内存使用率，最大分区使用率和交换分区使用率就会报“Only queries that return single series/table is supported”的错误。选择任意一台机器之后问题消失。只要选择All或者主机只有一台的情况下就会出现这种情况
> 
> ![image.png](https://camo.githubusercontent.com/1c391d97703817c5d80a9da83c9200e44a45b3b5/68747470733a2f2f62336c6f6766696c652e636f6d2f66696c652f323032302f30372f696d6167652d35376461613030342e706e67)
> 
> ![image.png](https://camo.githubusercontent.com/72aa5be1de792809f4f64c3a35826ec63be40d30/68747470733a2f2f62336c6f6766696c652e636f6d2f66696c652f323032302f30372f696d6167652d31336465663338302e706e67)

grafana使用7的版本的话，不需要使用兼容版了。直接使用新发布v20200628的看板就行。
https://grafana.com/grafana/dashboards/8919
