### ISSUE TITLE
点击主机明细后，链接会重写，重写后参数丢失，图形无法显示

### ISSUE THREAD

**Issue by hicaoc** [starsliao/Prometheus#50]
http://grafana.xx.com/d/9CWBz0bik/1-node-exporter-for-prometheus-dashboard-cn-v20200628?orgId=1&var-job=&var-hostname=&var-node=&var-device=

我修改了，从新窗口打开，参数正常，可以显示图形。 本窗口打开，参数丢失。 能看到过程，显示正常后，又自动刷没了。 是不是和本窗口的自动刷新有冲突

**Comment by starsliao** [comment]
> http://grafana.xx.com/d/9CWBz0bik/1-node-exporter-for-prometheus-dashboard-cn-v20200628?orgId=1&var-job=&var-hostname=&var-node=&var-device=
> 
> 我修改了，从新窗口打开，参数正常，可以显示图形。 本窗口打开，参数丢失。 能看到过程，显示正常后，又自动刷没了。 是不是和本窗口的自动刷新有冲突

之前版本的配置有点问题，这个最近会更新下，修正这个问题。
