### ISSUE TITLE
wmi_exporter 改名为 windows_exporter

### ISSUE THREAD

**Issue by netcore-jroger** [starsliao/Prometheus#51]
如题。
导入下载的 node_exporter for windows 的 json 配置文件后，没有正确展示。所有面板都没有数据。
[参见说明](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.13.0)

**Comment by starsliao** [comment]
gitlab的json是更新过的，可以试下：https://github.com/starsliao/Prometheus/tree/master/wmi_exporter

因为图表做了较多改动，之后会在grafana官网再更新一个版本。

**Comment by netcore-jroger** [comment]
谢谢！

**Comment by starsliao** [comment]
新版本已经发布了并做了一些优化
https://grafana.com/grafana/dashboards/10467
