### ISSUE TITLE
Why are you using fixed range selections instead of $__interval?

### ISSUE THREAD

**Issue by trallnag** [starsliao/Prometheus#52]
Just out of curiosity, since your dashboards are one of the more popular ones available in the Grafana Cloud: Is there any reason why you are using fixed range selections like `rate(metric[5m])` over the dynamic variable like `rate(metric[$__interval])`?

**Comment by starsliao** [comment]
Thank you for your suggestion, I will add dynamic variable in the next version。

**Comment by trallnag** [comment]
Please don't assume that I am an expert :smile: I'm just seeing many different ways people are graphing Prometheus metrics in Grafana and I'm wondering what the best approach might be
