### ISSUE TITLE
今天docker安装操作了一下，不显示数据

### ISSUE THREAD

**Issue by qifengzhang007** [starsliao/Prometheus#53]
#### 1.求一个qq群，或者微信群。  
> Node Exporter for Prometheus Dashboard 刚安装使用，竟然不显示数据，深受打击。
> 但是docker日志都没有报错。
>我是2020-08-05安装的docker环境（node_export+premetheus+grafana），docker拉取的都是  最新版本。
> 不知道为什么不显示数据， job  node   hostname 这几个变量没有获取到数据。

#### 2.官方公布的测试ok版本
> Grafana v7.0.1 + node_exporter 0.18.1测试使用正常 , 请告知一下 prometheus 版本是多少，我按照官方重新安装。

#### 3.配置部分
```code

# 看板说明 , 以下这段话涉及到的变量    job  node  这几个在我导入模板后还需要设置什么东西吗？

导入看板后，请根据实际情况在看板右上角点击Dashboard settings--Variables设置好变量：
默认已经设置并关联好job，hostname，node这3个变量。

$node取值node_exporter的instance，IP:端口格式。大部分查询关联了这个变量，请确保该变量有效！
$maxmount用来查询当前主机的最大分区，默认只获取ext.*和xfs类型的分区。

```

####  4.我的premotheus配置 ，我不知道哪里导致的获取不到数据，求指导
```code
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.

#A scrape configuration containing exactly one endpoint to scrape:
#Here it's Prometheus itself.
scrape_configs:
  #The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.6.12:9090']
        labels:
          instance: "prometheus"
  - job_name: "node"
    static_configs:
      - targets: ["192.168.6.12:9100"]
        labels:
          instance: "node"
```

####  5.2020-08-07 补充
> 我发现 premetheus 直接在物理机运行，grafana就可以获取服务器数据，但是通过docker方式启动的话，就获取不到数据。
> 我检查了prometheus.yml文件，对比了物理机的配置文件，格式和内容都是一样的，如上。
> 目前依然没有搞明白，为什么以docker运行 prometheus 就无法获取数据？
> 如果可能，请加一下我qq：1990850157， 直接在我服务器远程排查一下，不胜感激！

**Comment by qifengzhang007** [comment]
此问题解决了，但是我要曝光几篇垃圾博文，都是他妈互相抄袭，从来没有验证过是否最终成功。
其中一篇：
https://blog.csdn.net/Gushi150/article/details/90666559
该篇文章，尤其是  prometheus 的配置涉及到的大小写都是错误的，导致第一次使用被克重坑爹。
经历了2天，终于搞定了。
哎...

**Comment by starsliao** [comment]
不好意思 有几天没上github，目前没微信群，可以加我微信：starsliao  ，我会尽快创建一个微信群给大家交流。
