### ISSUE TITLE
English versions

### ISSUE THREAD

**Issue by FStefanni** [starsliao/Prometheus#55]
Hi,

I like your dashboards, but I can use only node exporter since it i sthe only one having an English version.
It could be nice (and very useful) to add translations also for the other two.

Can you please do this?
Best regards

**Comment by starsliao** [comment]
The windows_exporter dashboard will release an English version, and the blackbox_exporter dashboard has been released for too long, and a version will be optimized first.

**Comment by FStefanni** [comment]
Ok, then I can close these issue.
Thank you,
Regards.
