### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by FStefanni** [starsliao/Prometheus#56]
Hi,

I think I found a little bug.
In node exporter and windows exporter (I do not know blackbox, but probably), 
the url of subpath starts with a slash, preventing the correct management of the url in case grafana
is exposed on a sub url (as in my case).
For example, I expose grafana in `localhost/services/grafana`, behind a reverse proxy.

The fix is quite straightforward, please replace:
```
"linkUrl": "/d/hb7fSE0Zz...
```
with:
```
"linkUrl": "d/hb7fSE0Zz...
```
(note the missing starting slash).

Best regards

**Comment by starsliao** [comment]
Thanks, I will fix this bug
