### ISSUE TITLE
windows_exporter 资源总览表格列样式里的阈值和数据类型单位未对应

### ISSUE THREAD

**Issue by Diadormu** [starsliao/Prometheus#57]
Column Styles里C盘使用率(Value #E)和使用最多分区(Value #F)的Type Unit是 percent(0.0-1.0)，但在Thresholds那里依然为 60,80，应该对应改为 0.6,0.8，否则表格内颜色无法正常显示

**Comment by starsliao** [comment]
谢谢，我近期更新一下这个看板。
