### ISSUE TITLE
I can't see hosts (Port 9182 running in Prometheus but not grafana)

### ISSUE THREAD

**Issue by berekese** [starsliao/Prometheus#58]
Hi, 

I have node working in prometheus; http://IP:9182
I added your dashboard but I can't see my host windows, could you help me?

Thanks!

**Comment by starsliao** [comment]
Please confirm whether there is an error message in grafana? Need more information, may need to upgrade your grafana

**Comment by berekese** [comment]
No, I pasted your Dashboard, and I have servers running Port 9182 and working in prometheus (i see métrics) but when i put your Dashboard i cant see my severs. I tried with others Dashboard and works
I have latest versión grafana (7). How could solve It?
Thanks!!!

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by starsliao** [comment]
Is there a red mark in the upper left corner of the chart indicating an error message?
It is also possible that some variables have not obtained values, you can check the variables in the settings.

**Comment by berekese** [comment]
Thanks, there arent red marks on corner. I Will try in some days because im in holidays now :)

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________
