### ISSUE TITLE
Can you add support for victoriametrics?

### ISSUE THREAD

**Issue by denisgolius** [starsliao/Prometheus#59]
Add support for [victoriametrics](https://victoriametrics.com)
Because https://grafana.com/grafana/dashboards/1860 already can get data from [VM datasource ](https://grafana.com/grafana/dashboards/1860)

**Comment by starsliao** [comment]
I am going to replace my prometheus storage with victoriametrics.

But are they not compatible? Do I need to add Victoriametrics support to the grafana dashboard separately?

**Comment by denisgolius** [comment]
> I am going to replace my prometheus storage with victoriametrics.
> 
> But are they not compatible? Do I need to add Victoriametrics support to the grafana dashboard separately?

It fully compatible. Add new datasource with Prometheus type, but use [Victoriametrics](https://github.com/VictoriaMetrics/VictoriaMetrics#grafana-setup) address. You can always give a help on [Slack](http://slack.victoriametrics.com/) or [Github issues](https://github.com/VictoriaMetrics/VictoriaMetrics/issues) .

**Comment by starsliao** [comment]
> > 我将用victoriametrics替换我的prometheus存储。
> > 但是它们不兼容吗？我是否需要分别向grafana仪表板添加Victoriametrics支持？
> 
> 它完全兼容。添加具有Prometheus类型的新数据源，但使用[Victoriametrics](https://github.com/VictoriaMetrics/VictoriaMetrics#grafana-setup)地址。您总是可以在[Slack](http://slack.victoriametrics.com/)或[Github问题](https://github.com/VictoriaMetrics/VictoriaMetrics/issues)上获得帮助。

I tried to use Victoriametrics, and found the problem you mentioned in grafana: the table display will be abnormal.
Then I used Victoriametrics v1.38.1, and the table in grafana showed normal again.
This is the official link about this issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/720

**Comment by valyala** [comment]
FYI, it looks like the source of the issue has been identified and fixed at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/720 . The bugfix will be included in the next release of VictoriaMetrics.

**Comment by starsliao** [comment]
****
