### ISSUE TITLE
English translation 

### ISSUE THREAD

**Issue by s3ni0r** [starsliao/Prometheus#6]
Hi,
Thank you very much for the wonderful Grafana dashboard, would it be possible to provide an English translation for the few values that are not in English?
Thanks.

**Comment by starsliao** [comment]
> Hi,
> Thank you very much for the wonderful Grafana dashboard, would it be possible to provide an English translation for the few values that are not in English?
> Thanks.

Hi, I released an English version of the dashboard。

1 Node Exporter for Prometheus Dashboard English Version UPDATE 1102
https://grafana.com/grafana/dashboards/11074

**Comment by s3ni0r** [comment]
Hi,
Thank you for the great work :) !

**Comment by pineshmenat** [comment]
Could you also translate Windows Exporter to English, it would be of great help
