### ISSUE TITLE
下载带宽和上传带宽指的是什么？数字异常的大

### ISSUE THREAD

**Issue by fy0** [starsliao/Prometheus#60]
总览数据：
![image](https://user-images.githubusercontent.com/1579850/92851953-c33e6b00-f420-11ea-826d-ea392f84f655.png)

每秒数据面板又比较正常：
![image](https://user-images.githubusercontent.com/1579850/92852033-d5200e00-f420-11ea-8aad-c06be268b2ec.png)

**Comment by starsliao** [comment]
> 总览数据：
> ![image](https://user-images.githubusercontent.com/1579850/92851953-c33e6b00-f420-11ea-826d-ea392f84f655.png)
> 
> 每秒数据面板又比较正常：
> ![image](https://user-images.githubusercontent.com/1579850/92852033-d5200e00-f420-11ea-8aad-c06be268b2ec.png)

总览的带宽是取的当前主机的最大带宽的网卡的。你看下是否有多个网卡，上面菜单网卡选ALL

表达式是：
```
max(irate(node_network_receive_bytes_total{job=~"$job"}[5m])*8) by (instance)
```

**Comment by fy0** [comment]
那看来是内网的一些服务导致的，感谢回答
