### ISSUE TITLE
Certain fields not showing data

### ISSUE THREAD

**Issue by briantownjr** [starsliao/Prometheus#61]
Node exporter updated to 1.0.1.

Most recent version of dashboard.

Seems some disk related panels are not showing any info, disk I/O, R/W data, IOPs and R/W time.

**Comment by briantownjr** [comment]
Seems the issue was the interval variable, it was set to multiple values. As soon as I set it to a single value things showed up properly.

**Comment by starsliao** [comment]
> Seems the issue was the interval variable, it was set to multiple values. As soon as I set it to a single value things showed up properly.

The default time interval is set to 2 minutes. If your Prometheus `scrape_interval` is greater than 1 minute, the graph will not be displayed. Just choose a larger time interval.
