### ISSUE TITLE
我导入windwos_dashboad后，服务器资源总览显示无数据

### ISSUE THREAD

**Issue by zetterma** [starsliao/Prometheus#62]
我使用了1 Node Exporter for Prometheus Dashboard CN v20201010这个dashboard，导入后服务器资源总览显示无数据，但是我把intant取消后就能看到，不知道是什么原因，还请指教一下，谢谢

**Comment by starsliao** [comment]
> 我使用了1 Node Exporter for Prometheus Dashboard CN v20201010这个dashboard，导入后服务器资源总览显示无数据，但是我把intant取消后就能看到，不知道是什么原因，还请指教一下，谢谢

你说的`intant`是指的什么？ 有报错截图之类的么？

**Comment by zetterma** [comment]
是grafana的instant，报错没报错，就是没数据

**Comment by starsliao** [comment]
> 是grafana的instant，报错没报错，就是没数据

请复制无法展示的图表的promql到prometheus里面直接查询，然后看Console页面是否有数据。

这类问题一般是prometheus本身无法查询到实时数据，所以grafana也无法展示。

**Comment by zetterma** [comment]
> > 是grafana的instant，报错没报错，就是没数据
> 
> 请复制无法展示的图表的promql到prometheus里面直接查询，然后看Console页面是否有数据。
> 
> 这类问题一般是prometheus本身无法查询到实时数据，所以grafana也无法展示。

我试过promql，是可以查询到数据的。
