### ISSUE TITLE
Panel plugin not found: stat

### ISSUE THREAD

**Issue by saitiger008** [starsliao/Prometheus#63]
Grafana Enterprise v6.5.2 (742d165)
prometheus-2.20.1.linux-amd64
node_exporter-1.0.1.linux-amd64

运行时间  CPU核数  总内存   CPU iowait  剩余节点数  总文件描述符
以上六项内容无法显示，提示：Panel plugin not found: stat

**Comment by starsliao** [comment]
> Grafana Enterprise v6.5.2 (742d165)
> prometheus-2.20.1.linux-amd64
> node_exporter-1.0.1.linux-amd64
> 
> 运行时间 CPU核数 总内存 CPU iowait 剩余节点数 总文件描述符
> 以上六项内容无法显示，提示：Panel plugin not found: stat

不好意思，纯数字的那几个图表可能对6.x的grafana没做兼容，你可以直接修改下那几个图表的类型为singlestat
