### ISSUE TITLE
Add support for ZFS to node_exporter

### ISSUE THREAD

**Issue by martbhell** [starsliao/Prometheus#64]
Hello!

Thanks for an awesome dashboard!

Would be nice if this dashboard could also show ZFS file systems :)

I was trying to find the latest place for the latest grafana dashboard version but I couldn't find it. Could you point me in the direction and then I could make a PR there?

Something like below might work.
I used vim and ran `:%s/xfs\\/xfs|zfs\\/c` a bunch of times to make sure it changed the right things.

```bash
$ cat file.json|sed -e '/xfs\\/xfs|zfs\\/g'
```

**Comment by starsliao** [comment]
I thought about maintaining it on the grafana official website, so I deleted the json file of github, and now I re-upload it to github.
And I will add zfs support based on your suggestions. Thank you
