### ISSUE TITLE
blackbox_exporter

### ISSUE THREAD

**Issue by FunkyYang** [starsliao/Prometheus#66]
可否参考下 prometheus 关于blackbox部分的配置

**Comment by FunkyYang** [comment]
看了关闭的issue,发现用的consule,和我的需求不符合,我用的原生的blackbox_exporter,导入面板之后发现没有domain,ip,port这些metric 请问原生的能实现抓取这些指标？

**Comment by starsliao** [comment]
因长时间没有维护该看板，近期会优化一个版本。
