### ISSUE TITLE
节点没有自动更新

### ISSUE THREAD

**Issue by iT2afL0rd** [starsliao/Prometheus#7]
感谢提供的 Dashboard，实际是用的过程中发现当集群中有新的 Node 加入之后，`节点`的下拉框里面并不会同步更新。

我尝试把 node 变量改成了
```
label_values(node_exporter_build_info,instance)
```
也不起作用。
请问是我的配置问题吗？

**Comment by starsliao** [comment]
先确认下prometheus中是否有新加的节点，然后在grafana的变量配置中，查看下 Refresh设置的刷新情况，正常情况下应该在设置变量后，下面的预览框能看到相应的节点。
