### ISSUE TITLE
微服务等资源不显示

### ISSUE THREAD

**Issue by lwhua** [starsliao/Prometheus#70]
1 Kubernetes for Prometheus Dashboard CN v20201010 这个面板没有数据显示，kube-state-metrics安装了也没有数据。
如图所示：
![image](https://user-images.githubusercontent.com/6357279/98924463-d13b6580-250f-11eb-93dc-7b3f25a205c5.png)

![image](https://user-images.githubusercontent.com/6357279/98924584-f4661500-250f-11eb-9865-4faa0995ce65.png)

**Comment by lwhua** [comment]
原来是kube-state-metrics所属命名空间弄错了，但是还是有部分面板没有数据：
![image](https://user-images.githubusercontent.com/6357279/98927470-89b6d880-2513-11eb-917b-cff32cc04e23.png)

**Comment by starsliao** [comment]
遇到无数据的图表，请复制相应图表的promql到prometheus去查询，注意替换掉变量部分。

**Comment by joker-DT** [comment]
你的普罗米修斯你在k8s中部署的吗？
