### ISSUE TITLE
node_exporter 内存信息 存在过时 的 node_memory_MemAvailable_bytes   key

### ISSUE THREAD

**Issue by Ansen** [starsliao/Prometheus#72]
部分系统(我这只发现ubuntu 1404)已经不再支持 `node_memory_MemAvailable_bytes` 了，导致可用内存、已用内存、内存使用率不不显示

需要将 `node_memory_MemAvailable_bytes` 更新为 `node_memory_MemFree_bytes`

**Comment by Ansen** [comment]
根据官方 [issuse](https://github.com/prometheus/node_exporter/issues/608#issuecomment-310321494)  支持 `MemAvailable` 参数的最低内核版本为 3.1.4，而Linux中，严格来说：可用内存= `free` + `buff` + `cache`， 但是 `buff` 是块设备的缓冲，所以建议将 `MemAvailable`  配置为 ：free+cache,即：`node_memory_MemFree_bytes` + `node_memory_Cached_bytes`

**Comment by starsliao** [comment]
Duplicate of #18
