### ISSUE TITLE
求解变量 origin_prometheus

### ISSUE THREAD

**Issue by SHenry07** [starsliao/Prometheus#75]
1. `label_values(origin_prometheus)`请问这个有什么用？
2. 如果要监控两个不同集群的Prometheus 和这个变量有什么关系吗？

BR.

**Comment by SHenry07** [comment]
ooooo 我看到了这个，但是还是不是很理解， `Prometheus的外部系统标签` 这个要怎么查看呢？
> 新增数据源变量origin_prometheus，取自于Prometheus的外部系统标签：external_labels，可用于支持多个Prometheus接入VictoriaMetrics或Thanos等第三方存储使用remote_write方式的场景。(默认取值.*，指标中无该标签不影响使用)
VictoriaMetrics请使用v1.42.0及以上版本，修复了grafana表格展示的问题。

感谢

**Comment by zhaoqibin** [comment]
请教下这个变量要真么设置？我只有一个prometheus server

**Comment by rayshen3** [comment]
只有一个，保留为空就好吧

**Comment by yanggongwang** [comment]
是在prometheus的external_labels部分新增一个名为origin_prometheus的标签吗？
对grafana中数据源的名称有特殊要求吗？

**Comment by starsliao** [comment]
> 
> 
> ooooo 我看到了这个，但是还是不是很理解， `Prometheus的外部系统标签` 这个要怎么查看呢？
> 
> > 新增数据源变量origin_prometheus，取自于Prometheus的外部系统标签：external_labels，可用于支持多个Prometheus接入VictoriaMetrics或Thanos等第三方存储使用remote_write方式的场景。(默认取值.*，指标中无该标签不影响使用)
> > VictoriaMetrics请使用v1.42.0及以上版本，修复了grafana表格展示的问题。
> 
> 感谢

这个外部系统标签只能在非prometheus中查询到，比如从grafana中执行promql查询。
