### ISSUE TITLE
每小时流量和实时带宽信息无法显示，prometheus是有数据源的

### ISSUE THREAD

**Issue by jinqiangtop** [starsliao/Prometheus#82]

**Comment by Lionzj** [comment]
我也是一样无法显示,去掉了一些搜索条件项后暂时正常:
`sum (sum (rate (container_network_receive_bytes_total{origin_prometheus=~"$origin_prometheus",pod=~".*$Container.*",pod=~"$Pod",namespace=~"$NameSpace",node=~"^$Node$"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info) by(container) *8`
`sum (sum (rate (container_network_transmit_bytes_total{origin_prometheus=~"$origin_prometheus",pod=~".*$Container.*",pod=~"$Pod",namespace=~"$NameSpace",node=~"^$Node$"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info) by(container) *8`

**Comment by lff0305** [comment]
同样的问题.
原因是较新版本的kube-state-metrics导出的metric没有node这个label, 有的是instance
把panel定义里的node=... 改成instance=...就OK了.
或者在prometheus里面加个配置,从instance复制到node label

**Comment by LeoDemon** [comment]
@jinqiangtop @Lionzj @lff0305 @starsliao @boystray 

请问这个带宽最后乘以8是啥意思，，有小伙伴知道吗

**Comment by starsliao** [comment]
关于节点名称的标签，因为cadvisor是使用instance，而kube-state-metrics是使用node；这样会导致grafana节点信息表格中，没有统一的字段来连接各个查询，所以需要在prometheus.yaml中增加以下内容来给cadvisor的指标复制一个node标签。
```
    metric_relabel_configs:
    - source_labels: [instance]
      separator: ;
      regex: (.+)
      target_label: node
      replacement: $1
      action: replace
```
