### ISSUE TITLE
可以说一下如何安装prometheus才可以展示数据吗？

### ISSUE THREAD

**Issue by veryrich** [starsliao/Prometheus#84]
我按照网上的方法，搭建了很多次prometheus， 每次安装方式不同，就有不同的图表展示no data。。求大佬指点一二

**Comment by 54853315** [comment]
每个都有说要求的版本啊，一般6.x和7.x都可以用，建议用7.x，我这版基本很少有no data，除非是没有安装某个服务，但不影响。

**Comment by starsliao** [comment]
无数据 参考下https://github.com/starsliao/Prometheus/issues/70
