### ISSUE TITLE
node_exporter运行一段时间之后就显示的no data状态。用官方的可以一直正常显示数据。

### ISSUE THREAD

**Issue by langhaidian** [starsliao/Prometheus#90]
环境
OS：ubuntu 18.4 
软件：grafana v7.3.7 (1e261642f4)
node_exporter(本机部署): 1 Node Exporter for Prometheus Dashboard CN v20201010

问题：
1. 运行一段时间之后显示no data，服务一切正常。使用官方监控文件方式一直正常。
2. 显示no data查询结果如下：
    
<img width="1359" alt="WX20210311-180323@2x" src="https://user-images.githubusercontent.com/5392727/110770323-286dfe80-8294-11eb-989a-b8f4efba350b.png">

官方查询信息如下：
<img width="1424" alt="WX20210311-180125@2x" src="https://user-images.githubusercontent.com/5392727/110770374-36bc1a80-8294-11eb-8c4d-1a31ae850136.png">

3. 必须要重启系统才能看到新到监控数据。

**Comment by starsliao** [comment]
无数据 参考下 https://github.com/starsliao/Prometheus/issues/70
