### ISSUE TITLE
网络带宽显示不对

### ISSUE THREAD

**Issue by stilleshan** [starsliao/Prometheus#96]
服务端是使用 https://github.com/stefanprodan/dockprom docker compose部署.  
客户端也是使用这个compose里的nodeexporter,包括 volume 挂载也是一样.
  nodeexporter:
    image: prom/node-exporter:v1.1.2
    container_name: nodeexporter

---

使用 8919 模版
添加了一共6台服务器(均为centos7.x),其中网卡有 eth0和ens3两种,都显示很低的流量..与真实状况不符.

<img width="635" alt="截屏2021-05-08 17 22 28" src="https://user-images.githubusercontent.com/22582966/117534029-4781d600-b022-11eb-9b84-fec3ba055a2d.png">
<img width="687" alt="截屏2021-05-08 17 22 43" src="https://user-images.githubusercontent.com/22582966/117534032-48b30300-b022-11eb-979a-48a9d6c4cbd2.png">
<img width="554" alt="截屏2021-05-08 17 23 42" src="https://user-images.githubusercontent.com/22582966/117534034-49e43000-b022-11eb-96fd-368e86224135.png">

**Comment by stilleshan** [comment]
network必须host才正确..

**Comment by JacobHZ** [comment]
啊咧，具体是如何解决的呢，我也遇到了一样的问题。

**Comment by stilleshan** [comment]
> 啊咧，具体是如何解决的呢，我也遇到了一样的问题。

nodeexporter的网络改为
network_mode: host
